# Generated by Django 3.2.7 on 2021-10-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211019_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.TextField(blank=True, null=True, verbose_name='fullname'),
        ),
    ]
